# Generated by Django 5.2.2 on 2025-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationatily',
            field=models.CharField(blank=True, choices=[('AFG', 'Afghanistan'), ('DEU', 'Germany'), ('ARG', 'Argentina'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('BEL', 'Belgium'), ('BOL', 'Bolivia'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('KOR', 'South Korea'), ('CUB', 'Cuba'), ('DNK', 'Denmark'), ('EGY', 'Egypt'), ('ARE', 'United Arab Emirates'), ('ESP', 'Spain'), ('USA', 'United States'), ('PHL', 'Philippines'), ('FIN', 'Finland'), ('FRA', 'France'), ('GRC', 'Greece'), ('NLD', 'Netherlands'), ('HKG', 'Hong Kong'), ('HUN', 'Hungary'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISL', 'Iceland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('LBN', 'Lebanon'), ('MEX', 'Mexico'), ('MAR', 'Morocco'), ('NGA', 'Nigeria'), ('NOR', 'Norway'), ('NZL', 'New Zealand'), ('PAK', 'Pakistan'), ('PER', 'Peru'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('GBR', 'United Kingdom'), ('CZE', 'Czech Republic'), ('RUS', 'Russia'), ('SWE', 'Sweden'), ('THA', 'Thailand'), ('TUR', 'Turkey')], default='ESTADOS UNIDOS', max_length=3, null=True),
        ),
    ]
